### ISSUE TITLE
Syntax Error in Dependencies.scad

### ISSUE THREAD

**Issue by rogerw-gh** [sprabhakar2006/openSCAD#1]
Hi,  your modules look really useful,  I've tried using the filleted cylinder module and its throwing ERROR: Parser error in file "libraries/apexlib/dependencies.scad", line 108: syntax error - I am unable to find the syntax error :-( sorry.

**Comment by sprabhakar2006** [comment]
Hi
I don't have my computer right now with me
Please check if there is an extra comma at the end of let() statement
I am using the latest release of openscad.
Which version are you using?

**Comment by rogerw-gh** [comment]
Hi, no worries, this computer has 2019.05, there doesn't appear to be an extra comma at the end of the let.. checked all the brackets, round, square and curly... Will try a 2020 version later..

**Comment by sprabhakar2006** [comment]
Please try the latest development snapshot for your system

**Comment by sprabhakar2006** [comment]
Oh now I understand
In the latest version for squaring there is a shortcut symbol ^ which is
not supported in earlier versions
In that case try 2021 version

**Comment by rogerw-gh** [comment]
Ah, OK, I'll upgrade this machine,  given up trying to make dependencies.scad backwards compatible..

**Comment by rogerw-gh** [comment]
Might be worth mentioning that on your next release - thanks :-)

**Comment by sprabhakar2006** [comment]
Ok thanks
Did it finally worked?
